site_name: LoopDocumentation

extra_css:
    - css/version.css

markdown_extensions:
    - admonition
    - toc:
        permalink: true

plugins:
  - monorepo
  - search
  
theme:
  name: material
  custom_dir: overrides
  features:
      - navigation.tabs
      - toc.integrate