site_name: Loop Documentation

extra_css:
    - css/admonitions.css
markdown_extensions:
    - admonition
    - toc:
        permalink: ⌁

plugins:
  - monorepo
  - search
  
theme:
  name: material
  custom_dir: overrides
  features:
      - navigation.tabs

nav:
    - English: '!include ./docs/en/mkdocs.yml'
    - Dansk: '!include ./docs/da/mkdocs.yml'



