site_name: LoopDocumentation

extra_css:
   - "https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.0.0/css/flag-icon.min.css"

markdown_extensions:
  - meta
  - toc:
      toc_depth: 0
      
theme:
  name: material