# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install mkdocs-monorepo-plugin
      - run: pip install mkdocs-macros-plugin
      - run: mkdocs gh-deploy --force --config-file docs/da/mkdocs.yml --site_dir site/da
      - run: mkdocs gh-deploy --force --config-file docs/en/mkdocs.yml --site_dir site/en
