# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: workflow_dispatch
  # Triggers the workflow on push events but only for the main branch
  #push:
   # branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: mkdocs build --config-file loopdocs/mainsite/mkdocs.yml --site-dir ../site
      - run: mkdocs build --config-file loopdocs/da/mkdocs.yml --site-dir ../site/da
      - run: mkdocs build --config-file loopdocs/en/mkdocs.yml --site-dir ../site/en
      - run: mkdocs build --config-file loopdocs/de/mkdocs.yml --site-dir ../site/de
        
      - uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          BRANCH: gh-pages
          FOLDER: loopdocs/site
